### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by koyakoya1** [kamino410/phase-shifting#1]
Nice to meet you.
 First of all, thank you for making the phase shift program available.

 I have a question about the output result.
I don't know how to read the values ​​of display_y and display_x.  
I would appreciate it if you could give me an explanation.
 Sorry for the rudimentary question.
 
Also, for camera_y and camera_x, is it correct to understand that they are pix coordinates with the upper left as (0,0) in vizualized.png?

koyakoya1

**Comment by kamino410** [comment]
As you understand, `(y, x)` shows a pixel coordinate whose origin is on the upper left.
A row in the camera2display.csv (`camera_y, camera_x, display_y, display_x`) shows the following fact.
* Assume that the projector projects an image P to target objects and the camera captures an image C.
* The pixel `(camera_y, camera_x)` in the image C photographs the area being illuminated by the pixel `(display_y, display_x)` in the image P.

**Comment by koyakoya1** [comment]
Thank you very much for answering the question.
I understand.
